"""
Django settings for pdf_chat_project project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import dotenv_values

# Load environment variables from .env file
env_vars = dotenv_values(Path(__file__).resolve().parent.parent / ".env")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env_vars.get('SECRET_KEY', 'django-insecure-ov8^_j4cm4bx-cxcvm2ate+7lq4x+ok4w2f_6beh57(^h!ey4$')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_vars.get('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = env_vars.get('ALLOWED_HOSTS', '').split(',')
if '' in ALLOWED_HOSTS:
    ALLOWED_HOSTS.remove('')

# Determine environment
ENVIRONMENT = env_vars.get('ENVIRONMENT', 'UAT_LOCAL')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'chat_app',
    'storages', # Added for S3 storage
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pdf_chat_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pdf_chat_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Conditional AWS S3 settings
if ENVIRONMENT == 'UAT_AWS':
    AWS_ACCESS_KEY_ID = env_vars.get('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = env_vars.get('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = env_vars.get('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = env_vars.get('AWS_S3_REGION_NAME')
    # AWS_S3_ENDPOINT_URL = env_vars.get('AWS_S3_ENDPOINT_URL') # Optional

    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    AWS_LOCATION = 'media' # All files will be stored under this prefix in the S3 bucket
    MEDIA_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com/{AWS_LOCATION}/'
    AWS_S3_FILE_OVERWRITE = False # Prevent overwriting files with the same name
    AWS_DEFAULT_ACL = None # Or 'public-read' if files should be publicly accessible
    AWS_QUERYSTRING_AUTH = False # Don't add query parameters to S3 URLs

    # Ensure media root is still defined for local operations if needed, though S3 will handle storage
    MEDIA_ROOT = BASE_DIR / 'media_local_cache' # Use a local cache for media if needed
    print(f"DEBUG: DEFAULT_FILE_STORAGE is set to {DEFAULT_FILE_STORAGE}") # Added debug print
else: # UAT_LOCAL
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'
    print(f"DEBUG: DEFAULT_FILE_STORAGE is set to {MEDIA_ROOT}") # Added debug print

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
