# Generated by Django 5.2.8 on 2025-11-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat_app", "0002_pdfdocument_bm25_path_pdfdocument_docs_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pdfdocument",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="pdfdocument",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="pdfdocument",
            name="progress_percentage",
            field=models.IntegerField(default=0),
        ),
    ]
